filename=input("Enter the file name : ")
f1=open(filename,'w')
f1.write('Ethical Hacking\n')
f1.write('Cyber Security\n')
f1.write('Cyber Law\n')
f1.close()
f2=open(filename,'r')
data=f2.read()
print(data)
f2.close()
