filename1=input("Enter the file name 1: ")
f1=open(filename1,'w')
f1.write('Ethical Hacking\n')
f1.write('Cyber Security\n')
f1.write('Cyber Law\n')
f1.close()
f2=open(filename1,'r')
data1=f2.read()
print(data1)
f2.close()
filename2=input("Enter the file name 2: ")
f3=open(filename2,'w')
f3.write(data1)
f3.close()
f3=open(filename2,'r')
data2=f3.read()
print(data2)
f3.close()
